### PR TITLE
Create board member component

### PR DESCRIPTION
**Pull request by YosShimono**
Screenshot 2024-10-11 at 2 13 07 AM

### CODE REVIEW

**Comment by Kevinloritsch** [comment]
You're going to need some change some formatting things - we'll go over this during the meeting today.

**Comment by YosShimono** [comment]
Screenshot 2024-10-18 at 3 07 11 AM

**Review by Kevinloritsch — COMMENTED** [review]
nice!

**Review by Kevinloritsch — APPROVED** [review]

**Pull request merged**
