### PR TITLE
Added Title component with a line underneath

### PR DESCRIPTION
**Pull request by ThomasKofi2**

### CODE REVIEW

**Comment by Kevinloritsch** [comment]
You're going to need some change some formatting things - we'll go over this during the meeting today.

**Comment by ThomasKofi2** [comment]
Hi I will not be making it today, I messaged Mailyn to inform her already.
If you could please explain the changes I need to do that’ll be great.
Thank You

**Comment by Kevinloritsch** [comment]
Just sent you a discord friend request - we can setup a 1-1 meeting so that we can discuss everything 😄 !

**Comment by Kevinloritsch** [comment]
Can you make sure to always include an image when you make your pr?

**Comment by ThomasKofi2** [comment]
> Can you make sure to always include an image when you make your pr?

Yes

**Comment by ThomasKofi2** [comment]
Screenshot 2024-10-18 at 4 05 04 PM

**Comment by Kevinloritsch** [comment]
image
our goal is to match the figma as much as possible here!
could you try: making the line a bit thinner and less wide, and maybe a tiny bit lower?
don't forget to refer to: https://tailwindcss.com/

**Pull request merged**
