### PR TITLE
add "not found" component

### PR DESCRIPTION
**Pull request by Akshay-Jayaram**
image

Font style and custom button color are still pending

### CODE REVIEW

**Review by mailynnguyen — CHANGES_REQUESTED** [review]
Everything looks good. Only thing is with the spacing, can you make it look more like the Figma? Also, please shorten the line under 404 like in the Figma.

**Comment by mailynnguyen** [comment]
Also you might need to pull, there have been some updates to the remote repo.

**Comment by Akshay-Jayaram** [comment]
image

**Review by Kevinloritsch — APPROVED** [review]
Nice job!

**Pull request merged**
