### PR TITLE
edit font and spacing

### PR DESCRIPTION
**Pull request by Akshay-Jayaram**
image

Font, spacing and button color updated based on figma design

### CODE REVIEW

**Comment by Akshay-Jayaram** [comment]
There is no option to export the image as .webp format in Canva. Should I use an online converter?

**Comment by mailynnguyen** [comment]
Yes, perfect 👍🏼

**Review by mailynnguyen — CHANGES_REQUESTED** [review]
Please convert the drone.svg file to .webp.

Nice work :)

**Comment by Akshay-Jayaram** [comment]
Image changed from svg to webp

**Review by mailynnguyen — APPROVED** [review]

**Pull request merged**
