### PR TITLE
Member detail

### PR DESCRIPTION
**Pull request by XiyuanWu**
The background color can be changed.
image
image

I push the code without formatting it; it is easy to read when fixed.
I tried to use useState, but it ended up failing. I have no idea how useState work

### CODE REVIEW

**Comment by mailynnguyen** [comment]
useState takes in a variable and a function variable.

usually done like this: const [varName, setVarName] = useState(false)

// note that the arg inside the useState() can be anything - string, bool, etc.

we can define a function to change the state of the variable:

so for example

const functionName = () => {
    setVarName(!var);
}

**Comment by mailynnguyen** [comment]
so in regards to the board member pop up, u can do a state to check if board member has been clicked, show the pop up.

when you click on the board member it should trigger the function to change the click status (using useState) and then pop up the board member pop up.

hopefully this helps, send us a message if you need further help

**Comment by XiyuanWu** [comment]
> useState takes in a variable and a function variable.
> 
> usually done like this: const [varName, setVarName] = useState(false)
> 
> // note that the arg inside the useState() can be anything - string, bool, etc.
> 
> we can define a function to change the state of the variable:
> 
> so for example
> 
> const functionName = () => { setVarName(!var); }

Did you read the file? I did try first and I had the similar thing:  const [selectedMember, setSelectedMember] = useState<BoardMemberType | null>(null);
What you talk about it just a little and very roughly, even chatgpt are explained this better. This is not even a tailwind; this is javascript. Without learn it systematic, I have no idea what you talk about and how grammar work for javascript

**Comment by mailynnguyen** [comment]
Hey Xiyuan, I didn't understand your question. If you could be more direct next time, I would be able to understand it better. Would you like schedule a 1 on 1 to go over it? 

Also there is this document if you would like to look at it as well. React Docs: https://react.dev/reference/react/useState

Also, maybe cause it's online and messages can be construed, but I didn't appreciate when you said "even chatgpt explain better". I know my explanation was rough because it was through text and I didn't really understand your question. If you could explain more what you needed help with, it would help a lot.

**Comment by XiyuanWu** [comment]
@mailynnguyen 
I think we were both confused; I didn't quite get what you mean, too.
I do try to use GPT to help me do this, but it fails. The react we use here is a javascript library. But I have never learned JavaScript before, so I don't know how grammar works. Even though GPT had given the code, I couldn't understand what each line of code doing and didn't know where is the mistake. It's a very similar situation to the first time I coded Tailwindcss. 

I think I will watch a few videos during the break for this that will be ready for next quarter, like what I did early with Tailwind. But right now, as approach to the end of the quarter, I'm pretty busy and probably won't be able to catch up on my own, especially if you feel the project is already running behind. You can just sign this to someone else, but at least I done the static element.

Or if you have time, I don't mind a zoom if you can talk about it, but don't expect me code it right after it?

**Review by mailynnguyen — COMMENTED** [review]
Hey Xiyuan,

Ok, thank you for your message. Even though it was your first time with JavaScript, you were very close. I made some changes to to finish the effect up. Since I am also pretty busy right now with the end of the quarter and us being a little behind, I won't be able to do the 1 on 1. Sorry about that.

However, for some reason, the popup isn't showing up correctly during the popup but it shows correctly otherwise. This should just be some Tailwind issue. Can you fix that please?

Note: The popup closing doesn't work until you take out the gradient corners because it is covering the button. So you can take it out and put it back to test it if you'd like.

Please let me know if this didn't make sense or you have any questions.

**Comment by XiyuanWu** [comment]
I tried to remove the border, but it still didn't work; I don't know how popups work, too, I even don't know what "gradient corners" mean. To fix this issue, not just tailwind, I can't understand what code are doing after you fix them.
image

**Comment by mailynnguyen** [comment]
@XiyuanWu 

Ok, no worries Xiyuan. I'll assign it to someone else. Thank you for your work. Are you able to do an animation issue this week too, if you're familiar with Framer Motion?

**Comment by XiyuanWu** [comment]
It seems like Framer Motion is also a library of React. I will catch them up during the break.

**Comment by mailynnguyen** [comment]
Ok no worries. Thanks for letting me know.

**Pull request merged**
