### PR TITLE
Abhinav sharma/reccuring logo

### PR DESCRIPTION
**Pull request by abhnv-shrma**
Added Recurring Logo but Prettier edited the NotFound.tsx for some reason.

### CODE REVIEW

**Comment by Kevinloritsch** [comment]
can you include a picture of your issue on the pr? Just kinda a screenshot of what it looks like (not the code, but the rendered version)

**Review by mailynnguyen — CHANGES_REQUESTED** [review]
Please create a component that uses the logo image and create the white background for it. Let me know if you have any questions.

**Comment by abhnv-shrma** [comment]
image
 Changed to be the logo with a white background.

**Review by mailynnguyen — CHANGES_REQUESTED** [review]
All the styling is good, just make the height and width into percentages.
Make one component, and put the styles into that component, with the logo image.
Then you can call that component in the page.tsx files.

**Comment by abhnv-shrma** [comment]
Added percentages

**Review by Kevinloritsch — APPROVED** [review]

**Pull request merged**
