### PR TITLE
navbar start

### LINKED ISSUE #10: Create Navbar
image

### PR DESCRIPTION
**Pull request by arieen17**
image

- used placeholder for color/ default font (will fix once implemented)

### CODE REVIEW

**Review by mailynnguyen — CHANGES_REQUESTED** [review]
Can you try making the dividing lines a little thinner and the font a little bigger?

**Comment by arieen17** [comment]
image

**Comment by Kevinloritsch** [comment]
Did you run `npm run format`? It isn't passing formatting checks

**Review by Kevinloritsch — APPROVED** [review]
Great!

**Pull request merged**
