### PR TITLE
About Aviat

### LINKED ISSUE #7: Edit What Is Aviat'R Section Component
Edit font on this component, use Link-tag instead of a-tag.
Also, please check the arrow image, it's not working on our ends.

Image

### PR DESCRIPTION
**Pull request by XiyuanWu**
image

close #7

### CODE REVIEW

**Comment by Kevinloritsch** [comment]
Make sure to include a picture in your pr's!

**Comment by XiyuanWu** [comment]
i know, because this is not done and just save progress for me

**Review by mailynnguyen — APPROVED** [review]
Nice job!

**Comment by mailynnguyen** [comment]
Sorry, I missed something. Please change the font to be the correct font as in the Figma. Since I already merged this pr, you can just work from the same branch and create a new pull request.

**Pull request merged**
