### PR TITLE
Made some change on about aviat

### LINKED ISSUE #7: Edit What Is Aviat'R Section Component
Edit font on this component, use Link-tag instead of a-tag.
Also, please check the arrow image, it's not working on our ends.

Image

### PR DESCRIPTION
**Pull request by XiyuanWu**
image

Change:
Adjust font and size
Change padding number to percentage
Fix Image(The reason arrow image doesn't work is your guys change the path of the image)

close #7

### CODE REVIEW

**Review by mailynnguyen — CHANGES_REQUESTED** [review]
Nice work.
A few things:
- Make the component wider please
- Make the font for the "Mission Statement" larger and bolder (use "font-outline-4", can reference globals.css)
- Make the learn more text and arrow a little larger and longer please
- Make paragraph text a little longer and larger please

Overall, please make it a little bigger. Other than that, everything looks good.

**Comment by XiyuanWu** [comment]
image

**Comment by XiyuanWu** [comment]
image

**Review by mailynnguyen — APPROVED** [review]
Nice work.

**Pull request merged**
